name: Zihuatanejo
description: A warm place with no memory
meta_description: "Ben's Blog"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://wangbei.com'

# # Details for the RSS feed generator
# url:            'blog url'
author:         'Wang Bei'
