name: Zihuatanejo
description: A warm place with no memory
meta_description: "Ben's Blog"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'zealotrush.github.io'
author:         'Ben Wang'
