name: Zihuatanejo
description: Wang Bei
meta_description: "Wang Bei"

markdown: redcarpet
# markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
permalink: /:year/:month/:day/:title
domain_name: 'http://wangbei.com'

# Details for the RSS feed generator
url:            ''
author:         'Wang Bei'
