baseURL = "https://wangbei.me"
languageCode = 'zh-cmn'
defaultContentLanguage = 'zh-cmn'
title = 'Zihuatanejo'
author = '王备'
theme = 'emacs'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[markup.highlight]
noClasses = false

[params]
mainSections = ["posts"]
math = true
